### PR TITLE
stacks bitset coming soon

### PR DESCRIPTION
**Pull request by nurdtechie98**

### CODE REVIEW

**Comment by Chaitya62** [comment]
firse mistake 🙈😑

**Comment by Chaitya62** [comment]
mera mistake

**Comment by nurdtechie98** [comment]
Wait Karta Hun changes ko pull

**Comment by Chaitya62** [comment]
you and nishchit can now merge pull requests

**Comment by nurdtechie98** [comment]
🙌

**Comment by Chaitya62** [comment]
always use squash and merge

**Comment by inishchith** [comment]
spelling :X

**Comment by nurdtechie98** [comment]
Create an issue 😂

**Comment by Chaitya62** [comment]
Nishchith*

**Comment by inishchith** [comment]
😂 
btw only problems are left to add . i'll add it later .

**Pull request merged**
