### PR TITLE
Java Maps and Sets

### PR DESCRIPTION
**Pull request by hetzz**

### CODE REVIEW

**Comment by inishchith** [comment]
@hetzz Try to resolve the tabular view . Use [this](https://dillinger.io/) if needed .

**Comment by hetzz** [comment]
ON the atom editor it's getting displayed in a tabular form. I don't know what's wrong actually.

**Comment by inishchith** [comment]
I'll fix it . everything else done ?

**Comment by hetzz** [comment]
Yess

**Pull request merged**
