### PR TITLE
Queue sets

### PR DESCRIPTION
**Pull request by inishchith**
I'll add problems later .

### CODE REVIEW

**Comment by Chaitya62** [comment]
Merge conflicts 🙈 just pull the latest code and commit kar

**Comment by inishchith** [comment]
you merged #7 first  :P

**Comment by Chaitya62** [comment]
Ya, my mistake 🙈

**Comment by nurdtechie98** [comment]
even you link readme

**Comment by Chaitya62** [comment]
Ha

**Pull request merged**
